### ISSUE TITLE
Possible issue with Mono and ConditionalWeakTable

### ISSUE THREAD

**Issue by Sahasrara** [PeturDarri/GenericEventBus#1]
I came across this bug report for Mono and was wondering if that could cause issues using ConditionalWeakTable:
https://github.com/mono/mono/issues/13560

I guess it would only impact cases where devs create and delete event buses.

**Comment by PeturDarri** [comment]
Yeah, it was a mistake to use `ConditionalWeakTable`. It also has issues with IL2CPP in Unity. I have a branch (`wip/replace-conditional-weak-table`) that replaces it with an explicit dispose pattern, but haven't gotten around to merging it yet.

**Comment by PeturDarri** [comment]
Merged the branch.
